config/routes.rb
Rails.application.routes.draw do
  root to: "matches#index"
  resources :players
  resources :matches
  resources :leagues
  resources :clubs
end

app/models/club.rb
class Club < ApplicationRecord
  has_one_attached :logo

  has_many :home_matches, class_name: "Match", foreign_key: "home_team_id"
  has_many :away_matches, class_name: "Match", foreign_key: "away_team_id"
  has_many :players
  belongs_to :league

  def matches
    Match.where("home_team_id = ? OR away_team_id = ?", self.id, self.id)
  end

  def matches_on(year = nil)
    return nil unless year

    matches.where(kicked_off_at: Date.new(year, 1, 1).in_time_zone.all_year)
  end

  def won?(match)
    match.winner == self
  end

  def lost?(match)
    match.loser == self
  end

  def draw?(match)
    match.draw?
  end

  def win_on(year)
    year = Date.new(year, 1, 1)
    count = 0
    matches.where(kicked_off_at: year.all_year).each do |match|
      count += 1 if won?(match)
    end
    count
  end

  def lost_on(year)
    year = Date.new(year, 1, 1)
    count = 0
    matches.where(kicked_off_at: year.all_year).each do |match|
      count += 1 if lost?(match)
    end
    count
  end

  def draw_on(year)
    year = Date.new(year, 1, 1)
    count = 0
    matches.where(kicked_off_at: year.all_year).each do |match|
      count += 1 if draw?(match)
    end
    count
  end

  def homebase
    "#{hometown}, #{country}"
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    @players_average_age = (@club.players.sum(&:age) / @club.players.length).to_f
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def club_params
      params.require(:club).permit(:name, :established_on, :hometown, :country, :color, :manager)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= form_with(model: club, local: true) do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
        <% club.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :established_on %>
    <%= form.number_field :established_on %>
  </div>

  <div class="field">
    <%= form.label :hometown %>
    <%= form.text_field :hometown %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :manager %>
    <%= form.text_field :manager %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Established on</th>
      <th>Hometown</th>
      <th>Country</th>
      <th>Manager</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= club.established_on %></td>
        <td><%= club.hometown %></td>
        <td><%= club.country %></td>
        <td><%= club.manager %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>
    <h1>
      <%= @club.name %>
    </h1>

<section class="wrapper">
  <%= image_tag @club.logo, size: "250x250" %>

  <div>
    <p>
      <strong>Homebase:</strong>
      <%= @club.homebase %>
    </p>

    <p>
      <strong>Established on:</strong>
      <%= @club.established_on %>
    </p>

    <p>
      <strong>Manager:</strong>
      <%= @club.manager %>
    </p>

    <p>
      <strong>Results:</strong>
      <%= last_year %>: <%= @club.total_result_on(last_year) %>,
      <%= this_year %>: <%= @club.total_result_on(this_year) %>
    </p>

    <p>
      <strong>Players Avarage age</strong>
      <%= @players_average_age %>
    </p>

  </div>
</section>

<section>
  <p>
    <h1>Players:</h1>
    <table>
      <thead>
        <tr>
          <th>name</th>
          <th>position</th>
          <th>country</th>
          <th>age</th>
          <th>birthday</th>
        </tr>
      </thead>
      <tbody>
        <% @club.players.each do |player| %>
          <tr>
            <td><%= "#{player.firstname} #{player.lastname}" %></td>
            <td><%= player.position %></td>
            <td><%= player.country %></td>
            <td><%= player.age %></td>
            <td><%= player.birthday %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </p>
</section>

<%= link_to 'Back To Match Results', matches_path %>