config/routes.rb
Rails.application.routes.draw do
  root to: "matches#index"
  resources :players
  resources :matches
  resources :leagues
  resources :clubs
end

app/models/league.rb
class League < ApplicationRecord
  WIN_POINTS = 3
  DRAW_POINTS = 1

  has_many :matches
  has_many :clubs

  def table_rows(year=Time.current.year)
    rows = clubs.map { |club| Poros::LeagueTableRow.new(club, year).prepare_row }

    ranked_rows_by_points = rank_rows(rows)
    rank_rows_have_the_same_points(ranked_rows_by_points)
  end

  private

  def has_same_points_rows?(rows)
    rows.size != rows.map(&:points).uniq.size
  end

  def rank_rows(rows)
    rows_desc_sorted_by_points = rows.sort_by { |club| club.points }.reverse
    rows_desc_sorted_by_points.each { |row| row.rank = rows_desc_sorted_by_points.index(row) + 1 }
  end

  def rank_rows_have_the_same_points(rows)
    # Compare the two rows next to each other in the standings.
    # If the points are the same, the one with the most goal difference will be on top.
    # If the goal difference is the same, the one with the most wins per year will be ranked higher.
    # If they are still the same, they will be ranked in the same rate and displayed in dictionary order.
    return rows unless has_same_points_rows?(rows)

    rows.each_cons(2) do |upper_club, lower_club|
      if upper_club.goal_difference > lower_club.goal_difference
        next
      elsif upper_club.goal_difference < lower_club.goal_difference
        lower_club.rank = upper_club.rank
        upper_club.rank += 1
      elsif upper_club.goal_difference == lower_club.goal_difference
        if upper_club.win > lower_club.win
          next
        elsif upper_club.win < lower_club.win
          lower_club.rank = upper_club.rank
          upper_club.rank += 1
        elsif upper_club.win == lower_club.win
          lower_club.rank = upper_club.rank
        end
      end
    end
    rows.sort_by { |row| [row.rank, row.club.name] }
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def league_params
      params.require(:league).permit(:name, :country)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_with(model: league, local: true) do |form| %>
  <% if league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
        <% league.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leagues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= league.country %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= "#{@league.name} in #{last_year}" %></h2>
  <table>
    <thead>
      <tr>
        <th>Rank</th>
        <th>Club</th>
        <th>Digested Games Count</th>
        <th>Points *</th>
        <th>Win</th>
        <th>Draw</th>
        <th>Lost</th>
        <th>Goals</th>
        <th>Goals Conceded</th>
        <th>Goals Difference</th>
      </tr>
    </thead>

    <tbody>
      <% @league.table_rows(last_year).each do |row| %>
        <tr>
          <td><%= row.rank %></td>
          <td><%= row.club.name %></td>
          <td><%= row.digested_games_count %></td>
          <td><strong><%= row.points %></strong></td>
          <td><%= row.win %></td>
          <td><%= row.draw %></td>
          <td><%= row.lost %></td>
          <td><%= row.goals %></td>
          <td><%= row.goals_conceded %></td>
          <td><%= row.goal_difference %></td>
        </tr>
      <% end %>
    </tbody>
</table>

<p><%= "* Depending on the result of the match, points will be added as follows:
        #{League::WIN_POINTS} points per win, #{League::DRAW_POINTS} point per draw, no point per lost" %></p>

<%= link_to 'Back To Match Results', matches_path %>