config/routes.rb
Rails.application.routes.draw do
  root to: "matches#index"
  resources :players
  resources :matches
  resources :leagues
  resources :clubs
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :league
  belongs_to :home_team, class_name: "Club", foreign_key: "home_team_id"
  belongs_to :away_team, class_name: "Club", foreign_key: "away_team_id"

  scope :draw, -> { where("home_team_score = away_team_score") }

  validates :home_team_score, :away_team_score, presence: true
  validate :same_club_must_not_play_same_match

  def winner
    return nil if draw?

    if home_team_score > away_team_score
      home_team
    elsif away_team_score > home_team_score
      away_team
    end
  end

  def loser
    return nil if draw?

    if away_team_score > home_team_score
      home_team
    elsif home_team_score > away_team_score
      away_team
    end
  end

  def draw?
    home_team_score == away_team_score
  end

  def goal_by(club)
    if club == home_team
      home_team_score
    elsif club == away_team
      away_team_score
    else
      0
    end
  end

  def goal_conceded_by(club)
    if club == home_team
      away_team_score
    elsif club == away_team
      home_team_score
    else
      0
    end
  end

  private

  def same_club_must_not_play_same_match
    errors.add(:base, "home team and away team must be different") if home_team == away_team
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all.includes(:home_team, :away_team)
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:kicked_off_at, :league_id, :home_team_id, :away_team_id, :home_team_score, :away_team_score)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kicked_off_at %>
    <%= form.datetime_select :kicked_off_at %>
  </div>

  <div class="field">
    <%= form.label :league_id %>
    <%= form.select :league_id, League.all.collect { |p| [ p.name, p.id ] }, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :home_team_id %>
    <%= form.select :home_team_id, Club.all.collect { |p| [ p.name, p.id ] }, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :away_team_id %>
    <%= form.select :away_team_id, Club.all.collect { |p| [ p.name, p.id ] }, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :home_team_score %>
    <%= form.number_field :home_team_score %>
  </div>

  <div class="field">
    <%= form.label :away_team_score %>
    <%= form.number_field :away_team_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matche Results</h1>

<% League.all.each do |league| %>
    <div style="display: flex;">
      <h2><%= league.name %></h2>
      <%= link_to "Show league table", league, style: "margin: auto 35px;" %>
    </div>
    <table>
      <thead>
        <tr>
          <th>Kicked off at</th>
          <th>Home team</th>
          <th>Home team score</th>
          <th>Away team score</th>
          <th>Away team</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @matches.where(league: league).each do |match| %>
          <tr>
            <td><%= formatted_time_in(match.kicked_off_at, league.time_zone) %></td>
            <td><%= link_to match.home_team.name, match.home_team %></td>
            <td><%= match.home_team_score %></td>
            <td><%= match.away_team_score %></td>
            <td><%= link_to match.away_team.name, match.away_team %></td>
            <td><%= link_to 'Show', match %></td>
            <td><%= link_to 'Edit', edit_match_path(match) %></td>
            <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
<% end %>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kicked off at:</strong>
  <%= formatted_time_in(@match.kicked_off_at, @match.league.time_zone) %>
</p>

<p>
  <strong>League:</strong>
  <%= @match.league.name %>
</p>

<p>
  <strong>Home team:</strong>
  <%= @match.home_team.name %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @match.away_team.name %>
</p>

<p>
  <strong>Home team score:</strong>
  <%= @match.home_team_score %>
</p>

<p>
  <strong>Away team score:</strong>
  <%= @match.away_team_score %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>